import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import Provider from "@/components/providers";
import Footer from "@/components/footer/Footer";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Provider>
        <html lang="en">
          <body className={roboto.className}>
            {children}
            <Footer />
          </body>
        </html>
      </Provider>
    </>
  );
}
